import os
import glob
import json
import platform
import subprocess
from .scope_checker import scope_guard
from .logs_helper import log_path

WORDLISTS_DIR = "wordlists"


def _find_wordlist() -> str:
    """
    Return the best available wordlist path for this OS.

    Priority (Windows):
      1. wordlists/directory-list-2.3-medium.txt  (downloaded by installer — point #5)
      2. Any PATT wordlist in wordlists/patt_*.txt (generated by run_payloads — point #13)
      3. Return the default path even if absent (ffuf will fail with a clear error)

    Linux: use the system dirbuster list.
    """
    if platform.system() == "Windows":
        default = os.path.join(WORDLISTS_DIR, "directory-list-2.3-medium.txt")
        if os.path.exists(default):
            return default
        # Fallback — any PATT wordlist saved by run_payloads (#13)
        patt_lists = sorted(glob.glob(os.path.join(WORDLISTS_DIR, "patt_*.txt")))
        if patt_lists:
            return patt_lists[0]
        return default  # return path even if missing — ffuf will report the error clearly
    return "/usr/share/wordlists/dirbuster/directory-list-2.3-medium.txt"


def run(url: str, wordlist: str = "") -> str:
    guard = scope_guard(url)
    if guard:
        return guard

    if not wordlist:
        wordlist = _find_wordlist()

    output_path = log_path("ffuf.json")
    cmd = [
        "ffuf", "-u", url, "-w", wordlist,
        "-mc", "200,204,301,302,307,403",
        "-o", output_path, "-of", "json",
    ]
    try:
        result = subprocess.run(cmd, capture_output=True, text=True, timeout=180)
        if result.returncode != 0:
            return f"⚠️ ffuf exited with code {result.returncode}\n{result.stderr[-300:]}"

        try:
            with open(output_path, encoding="utf-8") as f:
                data = json.load(f)
            results = data.get("results", [])

            if not results:
                return "✅ ffuf done – 0 endpoints found"

            summary = f"✅ ffuf done – {len(results)} endpoints found:\n"
            for r in results[:15]:
                status = r.get("status", "?")
                found_url = r.get("url", "")
                if not found_url:
                    fuzz_val = (r.get("input") or {}).get("FUZZ", "?")
                    found_url = url.replace("FUZZ", fuzz_val)
                length = r.get("length", "?")
                summary += f"  [{status}] {found_url} ({length}b)\n"

            if len(results) > 15:
                summary += f"  ... +{len(results) - 15} more (use read_log 'ffuf.json')"
            return summary.strip()
        except Exception:
            return f"✅ ffuf done – results saved to {output_path}"
    except Exception as e:
        return f"❌ Erreur ffuf : {str(e)}"


TOOL_SPEC = {
    "name": "run_ffuf",
    "description": "Ultra-fast directory and endpoint fuzzing (ffuf). On Windows, auto-uses PATT wordlists if default is missing.",
    "input_schema": {
        "type": "object",
        "properties": {
            "url": {"type": "string"},
            "wordlist": {
                "type": "string",
                "description": "Wordlist path. Leave empty for auto-select. For injection fuzzing, use run_payloads first then pass the saved path.",
            },
        },
        "required": ["url"],
    },
}
