import os
import re
from datetime import datetime
from .logs_helper import log_path


def _md_to_html_body(content: str) -> str:
    """Minimal markdown → HTML conversion (no external deps)."""
    lines = content.split("\n")
    html = []
    in_code = False

    for line in lines:
        if line.startswith("```"):
            if in_code:
                html.append("</pre>")
                in_code = False
            else:
                lang = line[3:].strip()
                html.append(f'<pre class="code" data-lang="{lang}">')
                in_code = True
            continue

        if in_code:
            html.append(line.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;"))
            continue

        line = line.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
        line = re.sub(r'\*\*(.*?)\*\*', r'<strong>\1</strong>', line)
        line = re.sub(r'`(.*?)`', r'<code>\1</code>', line)

        if line.startswith("### "):
            html.append(f"<h3>{line[4:]}</h3>")
        elif line.startswith("## "):
            html.append(f"<h2>{line[3:]}</h2>")
        elif line.startswith("# "):
            html.append(f"<h1>{line[2:]}</h1>")
        elif line.startswith("- ") or line.startswith("* "):
            html.append(f"<li>{line[2:]}</li>")
        elif not line.strip():
            html.append("<br>")
        else:
            html.append(f"<p>{line}</p>")

    return "\n".join(html)


def run(title: str, content: str) -> str:
    ts = datetime.now().strftime("%Y%m%d_%H%M%S")
    md_path = log_path(f"report_{ts}.md")
    html_path = log_path(f"report_{ts}.html")

    with open(md_path, "w", encoding="utf-8") as f:
        f.write(f"# {title}\n\n_Generated by Phantom | {ts}_\n\n{content}")

    body = _md_to_html_body(content)
    html = f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Phantom — {title}</title>
  <style>
    body  {{ font-family: 'Courier New', monospace; background:#0d1117; color:#c9d1d9;
             max-width:960px; margin:40px auto; padding:0 24px; line-height:1.6; }}
    h1   {{ color:#f85149; border-bottom:2px solid #f85149; padding-bottom:10px; }}
    h2   {{ color:#58a6ff; background:#161b22; padding:8px 14px;
             border-left:4px solid #f85149; margin-top:30px; }}
    h3   {{ color:#79c0ff; margin-top:20px; }}
    pre  {{ background:#161b22; border:1px solid #30363d; padding:16px;
             border-radius:6px; overflow-x:auto; color:#a5d6ff; }}
    code {{ background:#161b22; padding:2px 6px; border-radius:3px; color:#ff7b72; }}
    li   {{ margin:4px 0; }}
    strong {{ color:#f85149; }}
    .meta {{ color:#6e7681; font-size:.9em; margin-bottom:28px; border-bottom:1px solid #21262d; padding-bottom:12px; }}
    .banner {{ background:#161b22; border:1px solid #30363d; border-radius:6px;
               padding:12px 16px; margin-bottom:24px; color:#58a6ff; letter-spacing:2px; }}
  </style>
</head>
<body>
  <div class="banner">[ PHANTOM ETHICAL REDTEAM — MISSION REPORT ]</div>
  <h1>🎯 {title}</h1>
  <div class="meta">Generated: {ts} | Phantom Ethical RedTeam</div>
  {body}
</body>
</html>"""

    with open(html_path, "w", encoding="utf-8") as f:
        f.write(html)

    return f"✅ Report saved:\n  Markdown : {md_path}\n  HTML     : {html_path}"


TOOL_SPEC = {
    "name": "generate_report",
    "description": (
        "Generate a formatted mission report (Markdown + HTML). "
        "Call at the end of the mission, before cleanup_temp, "
        "with the full executive summary, findings, PoC, and recommendations."
    ),
    "input_schema": {
        "type": "object",
        "properties": {
            "title": {
                "type": "string",
                "description": "Report title, e.g. 'Pentest Report — target.com — 2026-03-18'",
            },
            "content": {
                "type": "string",
                "description": "Full report body in Markdown format",
            },
        },
        "required": ["title", "content"],
    },
}
