# agent/main.py
import os
import sys
import yaml
import logging
from pathlib import Path

# Ensure agent/ is on sys.path
sys.path.insert(0, str(Path(__file__).parent))

# Force UTF-8 output on Windows (emoji support in tool results)
if sys.stdout.encoding and sys.stdout.encoding.lower() != "utf-8":
    sys.stdout.reconfigure(encoding="utf-8")
if sys.stderr.encoding and sys.stderr.encoding.lower() != "utf-8":
    sys.stderr.reconfigure(encoding="utf-8")

from tools.logs_helper import init_session
from agent_client import AgentClient
from providers import PROVIDERS

ROOT = Path(__file__).parent.parent

# Init session directory — all tool outputs will go to logs/<timestamp>/
os.chdir(ROOT)  # ensure relative paths resolve from project root
session_dir = init_session()

logging.basicConfig(
    filename=os.path.join(session_dir, "agent.log"),
    level=logging.INFO,
    format="%(asctime)s - %(levelname)s - %(message)s",
)

# CONFIG
with open(ROOT / "config.yaml") as f:
    config = yaml.safe_load(f)

with open(ROOT / "prompts" / "system_prompt.txt") as f:
    SYSTEM_PROMPT = f.read()

scope_path = ROOT / config.get("scope_file", "scopes/current_scope.md")
SCOPE = scope_path.read_text() if scope_path.exists() else ""

# Reject placeholder scope
if not SCOPE.strip() or "https://xxx" in SCOPE:
    print("❌ Invalid scope or placeholder detected. Fill in scopes/current_scope.md with an authorized target.")
    sys.exit(1)

# Load API key from .env if present (generated by install.sh / install.ps1)
env_file = ROOT / ".env"
if env_file.exists():
    for line in env_file.read_text().splitlines():
        if "=" in line and not line.startswith("#"):
            k, _, v = line.partition("=")
            os.environ.setdefault(k.strip(), v.strip())

provider = config.get("provider", "anthropic").lower()
interactive = config.get("interactive", True)
mode_label = "AUTONOMOUS" if config.get("autonomous", False) else "INTERACTIVE"

print("======================================")
print("  🚀 Phantom – Ethical RedTeam")
print(f"  Provider  : {provider.upper()}")
print(f"  Model     : {config.get('model') or 'default'}")
print(f"  Mode      : {mode_label}")
print(f"  Session   : {session_dir}")
print(f"  Scope     : {SCOPE.splitlines()[0]}")
print("======================================\n")

client = AgentClient(config=config)

messages = [
    {
        "role": "user",
        "content": (
            f"Authorized scope :\n{SCOPE}\n\n"
            "START THE MISSION IN AUTONOMOUS MODE. Think step by step, "
            "correct yourself, use the tools in sequence. "
            "Finish only with === MISSION COMPLETE === when it's done."
        ),
    }
]

turn = 0
max_turns = config.get("max_autonomous_turns", 50)

while turn < max_turns:
    try:
        messages = client.think(messages=messages, system_prompt=SYSTEM_PROMPT)

        # Extract text from last assistant message
        last_assistant = next(
            (m for m in reversed(messages) if m.get("role") == "assistant"), None
        )
        assistant_text = ""
        if last_assistant:
            content = last_assistant["content"]
            if isinstance(content, list):
                assistant_text = " ".join(
                    b.get("text", "") for b in content if b.get("type") == "text"
                )
            else:
                assistant_text = str(content)

        if "=== MISSION COMPLETE ===" in assistant_text:
            print("\n🎯 MISSION COMPLETE BY PHANTOM !")
            print(assistant_text.split("=== MISSION COMPLETE ===")[-1])
            break

        turn += 1

        if turn % config.get("pause_every_n_turns", 10) == 0:
            print(f"\n⏸️  Pause after {turn} steps.")
            if interactive and sys.stdin.isatty():
                cmd = input("Enter = continue | 'stop' = stop | 'report' = force report : ").strip().lower()
                if cmd == "stop":
                    break
                if cmd == "report":
                    messages.append({"role": "user", "content": "Generate final report now using generate_report tool."})
            else:
                print("  (non-interactive mode — continuing automatically)")

    except KeyboardInterrupt:
        print("\n👋 Mission aborted by user.")
        break
    except Exception as e:
        logging.error(f"Error : {e}")
        print(f"Error : {e}")
        break

print(f"\nPhantom stopped. Session logs: {session_dir}")
